### ISSUE TITLE
Issue on page /OCBE_II/Chapter 11 - Nucleophilic acyl substitution reactions.html

### ISSUE THREAD

**Issue by weisolyn** [c-bun/OCBE-Textbook#11]
Fixed text overlap on Figure 35.
[Figure35.txt](https://github.com/c-bun/OCBE-Textbook/files/10786048/Figure35.txt)

**Comment by c-bun** [comment]
Got it! I'll drop this in when I have a chance. Thanks!!

**Comment by c-bun** [comment]
Added. Thanks!
