### ISSUE TITLE
Issue on page /OCBE_I/Chapter 1 - Introduction to organic structure and bonding, part I.html

### ISSUE THREAD

**Issue by seergaem** [c-bun/OCBE-Textbook#2]
The text on the figure is doubled on itself, and needs to be fixed

**Comment by c-bun** [comment]
Yeah, there are a lot of figure issues. If you redraw the figure in chemdraw and submit it here I'll give you the extra credit!

**Comment by c-bun** [comment]
Just pinging this again. If you redraw the figure and submit it you'll get credit. See the video I posted on panopto for how to do it!
