### ISSUE TITLE
Issue on page /OCBE_II/Chapter 13 - Reactions at the ⍺-carbon, part II.html

### ISSUE THREAD

**Issue by Heltong** [c-bun/OCBE-Textbook#23]
![image](https://user-images.githubusercontent.com/112489896/229671420-833d46f1-8c15-4aea-9176-aa8f3ff1d809.png)
Fixed issue with the color-coding of 13.3A: Claisen Condensation's fig 31, specifically the middle molecules C and Nu.

**Comment by c-bun** [comment]
This looks great. But I can't use an image, it needs to be a chemdraw file. Follow the video on Panopto for how to upload the chemdraw file.
