### ISSUE TITLE
Issue on page /OCBE_II/Chapter 16 - Free radical reactions.html

### ISSUE THREAD

**Issue by juliburs** [c-bun/OCBE-Textbook#27]
Figure 27 Section 16.6 Flavin as a single electron carrier - fixed figure (structure 2 was missing arrows on top blue H, arrow from base to H and arrow from the NH bond to N)

[fig 27 Section 16.6- Flavin as a a single-electron carrier copy.txt](https://github.com/c-bun/OCBE-Textbook/files/11236458/fig.27.Section.16.6-.Flavin.as.a.a.single-electron.carrier.copy.txt)

**Comment by c-bun** [comment]
Got it! Thanks!
