### ISSUE TITLE
Issue on page /OCBE_II/Chapter 16 - Free radical reactions.html

### ISSUE THREAD

**Issue by juliburs** [c-bun/OCBE-Textbook#29]
Fig 1a chapter 16 -text overlap "spontaneous tautomerization" and [FADH2] instead of (FADH]

[fig 1a ch 16  copy.txt](https://github.com/c-bun/OCBE-Textbook/files/11236738/fig.1a.ch.16.copy.txt)

**Comment by c-bun** [comment]
got it! Thanks!
