### ISSUE TITLE
Issue on page /OCBE_II/Chapter 9 - Phosphate Transfer Reactions.html

### ISSUE THREAD

**Issue by asieduE** [c-bun/OCBE-Textbook#41]
For 9.7 Figure 41 the text was cut off
[9.7 Figure 41.txt](https://github.com/c-bun/OCBE-Textbook/files/11401479/9.7.Figure.41.txt)

**Comment by c-bun** [comment]
got it. thanks! For the next one, make sure you use acs 1996 settings.

**Comment by asieduE** [comment]
Thank you! I’m still submitting but what do you mean by acs 1996? Additionally, figures with text mistakes still count as a figure correction right?

Best,

Eliana Asiedu

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
