### ISSUE TITLE
Issue on page /OCBE_II/Chapter 9 - Phosphate Transfer Reactions.html

### ISSUE THREAD

**Issue by yunsong600** [c-bun/OCBE-Textbook#8]
Exercise 9.10 Edited product that had extra hydrogen in the product. There should be a negative charge on the oxygen atom instead of hydrogen. 
[Edition on exercise Ch 9.10.txt](https://github.com/c-bun/OCBE-Textbook/files/10712492/Edition.on.excercise.Ch.9.10.txt)

**Comment by c-bun** [comment]
Did you work on this with Seble?

**Comment by yunsong600** [comment]
Yes, I did.
