### ISSUE TITLE
Issue on page /OCBE_II/Chapter 9 - Phosphate Transfer Reactions.html

### ISSUE THREAD

**Issue by seblimehari** [c-bun/OCBE-Textbook#9]
Your issue content here. In exercise 9.10, the product in the reaction has one extra hydrogen. There should be a negative charge there instead of hydrogen. 
[Edition on excercise Ch 9.10.txt](https://github.com/c-bun/OCBE-Textbook/files/10712509/Edition.on.excercise.Ch.9.10.txt)

**Comment by c-bun** [comment]
Looks like both you and Song worked on this?

**Comment by seblimehari** [comment]
Yes we did, we found the error together while studying.
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
